# Generated by Django 2.2.24 on 2021-10-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='lei',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='maturity',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='size',
        ),
    ]
