# Generated by Django 2.2.24 on 2021-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_auto_20211014_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='bond',
            name='lei',
            field=models.CharField(default='12345678', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='maturity',
            field=models.DateField(default='2025-08-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='size',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
