# Generated by Django 2.2.24 on 2021-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20211014_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(default='BNPPARIBAS', max_length=20),
            preserve_default=False,
        ),
    ]
