# Generated by Django 2.2.24 on 2021-10-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0010_remove_bond_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(default='qwer', max_length=50),
            preserve_default=False,
        ),
    ]
